version: "3.3"
services:
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/test-app
      - bundle_install:/test-app/vender/bundle
volumes:
  bundle_install:
    driver: local