version: "3.3"
services:
  mysql:
    image: mysql:5.7.17
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: ./docker/.mysql_env
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    env_file: ./docker/.mysql_env
    ports:
      - 3000:3000
    volumes:
      - .:/test-app
      - bundle_install:/test-app/vender/bundle
    depends_on:
      - mysql
volumes:
  bundle_install:
    driver: local
  mysql_data:
    driver: local